// Generated by CoffeeScript 1.7.1
var tacly;

tacly = tacly || {};

tacly.ticTacToeApp = angular.module("ticTacToeApp", []);

tacly.TictactoeController = function($scope) {
  $scope.board = board;
  return $scope.tiles = [];
};
